apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-loadbalancer-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-pod
  type: LoadBalancer
